/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gualterosky (https://sketchfab.com/Gualterosky)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lobo-minecraft-04ba9c4fc3de430da18b6ae70d4b6a22
Title: Lobo Minecraft
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const MCDog = (props) => {
  const { nodes, materials } = useGLTF('/models/lobo_minecraft.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.StandardClone}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/lobo_minecraft.glb')
