/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Red Fox / nokillnando (https://sketchfab.com/nokillnando)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mfp-office-printer-d55f6fca7c3d45c883bbff770672970d
Title: MFP Office Printer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Printer = (props) => {
  const { nodes, materials } = useGLTF('/models/mfp_office_printer.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -1.832, 17.208]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial.geometry}
              material={materials.PrinterDrawerHandle}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_1.geometry}
              material={materials.PrinterBodyTray}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_2.geometry}
              material={materials.PrinterBodyDark}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_3.geometry}
              material={materials.PrinterPlasticVeryDark}
            />
          </group>
          <group position={[0, -32.365, 17.208]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_6.geometry}
              material={materials.PrinterDrawerHandle}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_7.geometry}
              material={materials.PrinterBodyTray}
            />
          </group>
          <group position={[0, -17.108, 17.208]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_8.geometry}
              material={materials.PrinterDrawerHandle}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_9.geometry}
              material={materials.PrinterBodyTray}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_11.geometry}
              material={materials.PrinterBlackStuff}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_12.geometry}
              material={materials.PrinterBody}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_13.geometry}
              material={materials.PrinterScreenMenu}
            />
          </group>
          <group position={[-21.922, 40, 7.084]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_17.geometry}
              material={materials.PrinterBlackStuff}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_18.geometry}
              material={materials.PrinterPlasticDark}
            />
          </group>
          <group position={[-20, 45.752, 7.084]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_19.geometry}
              material={materials.PrinterPlasticLight}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_20.geometry}
              material={materials.PrinterBlackStuff}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials.PrinterPlasticLight}
            position={[-61.222, 70.279, 7.084]}
            rotation={[-Math.PI / 2, Math.PI / 6, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_5.geometry}
            material={materials.PrinterBody}
            position={[-7.84, 81.545, -25.683]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_10.geometry}
            material={materials.PrinterPlasticLight}
            position={[27.171, 79.65, 5.221]}
            rotation={[-Math.PI / 2, -0.253, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_14.geometry}
            material={materials.PrinterPlasticLight}
            position={[-27.34, 53.539, 31.312]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_15.geometry}
            material={materials.PrinterPlasticLight}
            position={[-61.203, 48.375, 7.084]}
            rotation={[-Math.PI / 2, Math.PI / 6, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_16.geometry}
            material={materials.PrinterPlasticDark}
            position={[-35.266, 31.065, 7.084]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/mfp_office_printer.glb')