
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Youssef_0356 (https://sketchfab.com/nejiyoussef081)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/aws-logo-8aefa880ecee48778c4b3725b62c0649
Title: AWS Logo
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import {useFrame } from '@react-three/fiber';
import * as THREE from 'three';
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

export const AWSLogo = (props) => {
  const { nodes, materials } = useGLTF('/models/aws_logo.glb')
    // Continuously rotate the logo around the Y-axis
    const groupRef = useRef();
    useGSAP(()=>{
      gsap.to(groupRef.current.position, {
        y:groupRef.current.position.y+5.5,
        duration:2,
        repeat:-1,
        yoyo: true
      })
    })
  return (
    <group {...props} dispose={null} ref={groupRef}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ArrowBody_Material001_0.geometry}
          material={new THREE.MeshLambertMaterial({ color: new THREE.Color(0xFF5733) })}
          position={[-13.076, 155.698, -20.264]}
          scale={16067.461}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AWS_Material003_0.geometry}
          material={materials['Material.003']}
          position={[41.538, 612.01, -20.264]}
          scale={16067.461}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ArrowHead_Material001_0.geometry}
          material={new THREE.MeshStandardMaterial({ color: new THREE.Color(0xFF5733) })}
          position={[593.304, 205.677, -20.264]}
          scale={16067.461}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/aws_logo.glb')