
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Youssef_0356 (https://sketchfab.com/nejiyoussef081)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/aws-logo-8aefa880ecee48778c4b3725b62c0649
Title: AWS Logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame } from '@react-three/fiber'

export const VisualLogo = (props) => {
  const { nodes, materials } = useGLTF('/models/visual_studio_logo.glb')
    // Continuously rotate the logo around the Y-axis
    const groupRef = useRef();
    useFrame(() => {
        if (groupRef.current) {
          groupRef.current.rotation.y += 0.01  // Adjust the speed by changing the value
        }
      })
      return (
        <group {...props} dispose={null} ref={groupRef}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_2.geometry}
            material={materials.VisualS}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      )
}

useGLTF.preload('/models/visual_studio_logo.glb')